# Generated by Django 4.2 on 2025-07-02 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('labour', 'Labour Charge'), ('storage', 'Storage Charge'), ('tax', 'Internal Tax'), ('godown', 'Godown Charge')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='adminpanel.category')),
            ],
            options={
                'unique_together': {('category', 'charge_type')},
            },
        ),
    ]
