# Generated by Django 4.2 on 2025-06-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_paymentchargedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentchargedetail',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymentchargedetail',
            name='per_day_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='paymentchargedetail',
            table='payment_charge_details',
        ),
    ]
