# Generated by Django 4.2 on 2025-06-23 08:33

import adminpanel.models.category
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=adminpanel.models.category.category_image_path),
        ),
    ]
